# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'g3rv4'
tagline:          'Gervasio Marchand'
description:      'A blog written by a <i>very</i> lucky nerd'
meta_description: "Welcome to my blog. I'm Gervasio, currently working as a developer at Stack Overflow. I'm a nerd that loves doing nerdy stuff (unless it involves nerd movies)"
meta_tags:        ['blog', 'nerd', 'gervasio marchand', 'programming']
url:              https://g3rv4.com
baseurl:          /

author:
  name:           'Gervasio Marchand'
  url:            https://twitter.com/g3rv4

paginate:         30
excerpt_separator: <!--more-->

extlinks:
  attributes: {rel: nofollow, target: _blank}
  check_links: false
  check_exclude: ['twitter.com', 'disqus.com']
#  rel_exclude: ['host1.com', 'host2.net']

page_gen:
  - data: tags
    template: tag
    name: tag
    dir: tags
    dirs: true

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]
