# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: templates
      endpoint: g3rv4
      type: github
      name: g3rv4/AzurePipelinesTemplates

stages:
- template: agent-provision.yml@templates
- stage: Build
  pool: default
  jobs:
  - job: Build
    workspace:
      clean: all
    steps:
    - powershell: |
        sed -i '/#local/d' _config.yml
        sed -i 's/#prod://g' _config.yml

        $hash = '$(Build.SourceVersion)'
        $buildId = '$(Build.BuildId)'
        $version = "$($hash.Substring(0, 7)).$buildId"
        $version > _data/version.json

        Write-Host "##vso[build.updatebuildnumber]$($version)"

        $pwd = pwd
        $uid = sh -c 'id -u'
        $gid = sh -c 'id -g'

        docker run --rm -v "$($pwd):/var/site-content" g3rv4/blog-builder bash -c "/root/.rbenv/shims/jekyll build && chown -R $($uid):$($gid) /var/site-content"
        if($LASTEXITCODE){
            Exit $LASTEXITCODE
        }
      failOnStderr: false
    - publish: '_site'
      artifact: 'site'
