# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.SourceVersion)$(Rev:.r)

trigger:
- master

pool: default

- stage: Build
  jobs:
  - job: Build
    steps:
    - powershell: |
        sed -i '/#local/d' _config.yml
        sed -i 's/#prod://g' _config.yml
        docker run --rm -v .:/var/site-content g3rv4/blog-builder /root/.rbenv/shims/jekyll build 2>&1
